### ISSUE TITLE
Improve Jpackage release

### ISSUE THREAD

**Issue by fgnm** [rednblackgames/HyperLap2D#1]
Jpackage releases should be better for Windows and Linux.

### Windows

- [x] Permission problem when try to install in `C:\Program Files\HyperLap2D`, it appears to not have enough permission to write in that folder
- [x] remove `--win-per-user-install`
- [ ] Add much more icons and descriptions to the setup program

### Linux

- [x] Add much more icons and descriptions to meta

### macOS

- [x] TODO..

**Comment by payne911** [comment]
The ``jar`` that is released isn't executable and I still had to use ``java -jar`` to open it. :(

**Comment by fgnm** [comment]
Which OS?
Anyway I **highly** suggests to clone repo and run with IntelliJ becuase some bug fixes (i.e. crazy CPU when minimized). Since now jpackage works well for any OS, I think that today or tomorrow I'll setup the Github action to pack `deb`, `msi` and `dmg` automatically so it will be easy to update the program in this alpha stage. Instead, `jar` release will be discontinued because requires Java 14 and many does't have it..

**Comment by payne911** [comment]
> Which OS?

Windows 10.

**Comment by fgnm** [comment]
> 
> Windows 10.
>
So master branch will work much better, CPU will be thankful 😅 
>
> > Instead, jar release will be discontinued because requires Java 14 and many does't have it..
> 
> Use JLink to package a custom JRE instead. I think this might help you: https://www.youtube.com/watch?v=R7CMXeQ11GM
I use it too :)

**Comment by fgnm** [comment]
It was much more easy then expected :smile: 
Since now, installation packages are build with Github actions and delivered as artifacts: https://github.com/rednblackgames/HyperLap2D/actions/runs/227290744

**Comment by payne911** [comment]
You should probably close this issue now that it's resolved.

**Comment by fgnm** [comment]
Well, not exactly. I'd like to create a custom WiX installer with banners, icons and some other graphical stuff; for Linux at least make the icon visible in software center when double click on `.deb`; and for macOS figure out why when built with Github actions it does not recognize dmg background and post script.
