### ISSUE TITLE
README > Mention java version

### ISSUE THREAD

**Issue by Minecraftian14** [rednblackgames/HyperLap2D#13]
Please 🙏 mention in the _readme_ of your project that the **JAR build** requires _Java 14_.

Thanks to the fact that I know what version 58 means and that i have many java version installed, I was able to run the app.
But for those new to java, and libgdx they wont be able to use the app in the first place 😋!

Thanks a lot.

**Comment by Minecraftian14** [comment]
... Well that's another thing that you also provide platform specific builds, but when you are also giving a jar, just place the text somewhere

**Comment by fgnm** [comment]
Thanks!
Just to add on this, further releases (and current snapshots) will be released with integrated JRE (in `.exe`, `.deb` and `.dmg`), so users don't need to have Java 14 installed. `.jar` release will be discontinued from the next release.
