### ISSUE TITLE
Cant launch HyperLap editor on ubuntu V0.0.2

### ISSUE THREAD

**Issue by PotaytoPrograms** [rednblackgames/HyperLap2D#18]
I could launch v0.0.1 however for some reason v0.0.2 cant be launched.
I installed HyperLap 0.0.2 using the deb package and did the same with the previous version.
When I launch it the splash screen appears and then after a while it disappears and the program hasn't launched.

**Comment by fgnm** [comment]
Could you please try latest snapshot? https://github.com/rednblackgames/HyperLap2D/actions/runs/310508419

There where an issue already fixed that might prevent program to be launched https://github.com/rednblackgames/HyperLap2D/commit/9a5dfd5610a6095927f2a2bc2f6715cc1cbb7a26

**Comment by PotaytoPrograms** [comment]
Thank you it worked
