### ISSUE TITLE
top down RTS support?

### ISSUE THREAD

**Issue by eix128** [rednblackgames/HyperLap2D#24]
Hi , is there any support/sample for top down RTS style ?
like Warcraft 2
2- ) Can we donate or buy license?

You should also put demos on youtube

**Comment by fgnm** [comment]
Hi, well HyperLap2D itself is just an Editor to helps you design the world of your game. It can be used for many purposes and different kind of games, including top down. After the design phase, you should program the logic yourself. Currently there's the libGDX runtime, a library that you can use in a libGDX project that helps you to render content created with this Editor (plus some helpful stuff).
An RTS game like Warcraft 2 can be surely made with libGDX, but it really depends on your programming skills, anyway this Editor (along with some other tools) will helps a lot while doing that!
I suggest you to join both HyperLap2D and libGDX Discord servers, whatever you are a beginner or a pro we try always to help :)

I close this issue becuase Github is to keep track of bugs and issues, Discord is a better place to talk this kind of stuff
