### ISSUE TITLE
 Change the order / position of the images in composite mode

### ISSUE THREAD

**Issue by aallnneess** [rednblackgames/HyperLap2D#28]
It would be good if it were possible to change the position of the image in composite mode (Items Tree).
Because at the moment every new image overwrites the old one.

Sometimes this is not wanted.

Example: I am building an island and starting with the beach. Now I position palm trees on the beach. I notice that it would be nicer if some palm trees were positioned behind the beach. But unfortunately I can't push palm trees behind the beach in the item tree order.

![image](https://user-images.githubusercontent.com/73443724/109815217-ad6f6d00-7c2f-11eb-9861-541e17b4c631.png)

**Comment by fgnm** [comment]
Currently you can't drag and drop items in tree view, but you can change z-index using shortcuts. Select an item and use:

- `Ctrl + ↑` (`⌘ + ↑`) : Z-index change up

- `Ctrl + ↓` (`⌘ + ↓`) : Z-index change down

Shortcut list [here](https://github.com/rednblackgames/HyperLap2D/wiki/Shortcuts)
