### ISSUE TITLE
Sprite Animation freeze using SpriteAnimationComponent / SpriteAnimationStateComponent

### ISSUE THREAD

**Issue by aallnneess** [rednblackgames/HyperLap2D#31]
**Problem:**
Sprite Animation freeze using SpriteAnimationComponent / SpriteAnimationStateComponent.
The first image of the animation is loaded, but no animation.

Ive build an playerSpriteManager method, called in the render function:

`  private void playerSpriteManager(){

        SpriteAnimationComponent spriteAnimationComponent = ComponentRetriever.get(player,SpriteAnimationComponent.class);
        SpriteAnimationStateComponent spriteAnimationStateComponent = ComponentRetriever.get(player,SpriteAnimationStateComponent.class);

        spriteAnimationComponent.fps = 24;
        spriteAnimationComponent.currentAnimation = "walk";
        spriteAnimationComponent.playMode = Animation.PlayMode.LOOP;

        spriteAnimationStateComponent.set(spriteAnimationComponent);

    }`

**Inside h2d:**

- Import Sprite png's to h2d as one numbered sequence of images.
- Edit Sprite Animation Ranges (walk, idle and Default)
- Sprite Animation is still not a composite
- added Polygon and Physics to Sprite Animation
- All animation's work well inside h2s editor

Hyperlap 0.0.6-Snapshot
Windows 10 64bit
Intellij 
OpenSk 15

**Comment by fgnm** [comment]
Not a issue :smile:

**Comment by aallnneess** [comment]
shame on me 😜

My mistake: animation was restarted in every frame.
