### ISSUE TITLE
Save sprite animation to library

### ISSUE THREAD

**Issue by aallnneess** [rednblackgames/HyperLap2D#33]
It's a very nice way to save composites in the library. Once created, it can be used anywhere in the project at any time.

If I insert a sprite in the editor and edit the animation loops, it would be nice to also be able to save the spite with its settings and be able to reload it later at any time.

**Optional:** Export edited sprites included png's (with the possibility of importing them into other h2d projects.)

**Comment by fgnm** [comment]
You can wrap whatever you want into a composite and save it as a library item. Then, you can export it as `h2dlib` format (it's a zip that contains all required resources) and import in any other project.

https://github.com/rednblackgames/HyperLap2D/wiki/Import-Export-Library-items

There might be some issues with projects that have different PPWU, should be tested a bit more :)

**Comment by aallnneess** [comment]
Hm. Okay, with Itemwarpper i can get the sprite ingame and animate it well.
But, physics i must add to composite to make it work. But, composite is ingame no enitiy ? 

![image](https://user-images.githubusercontent.com/73443724/110612092-2589e580-8190-11eb-95a8-cd3d8a469ecb.png)

(when i only add physics to the sprite inside the composite - nothing happends ingame. so i thing i must take action the x/y pos. from the composite....but when i want to work with box2d - and the composite is no entity.... ? :D )

**Comment by fgnm** [comment]
Composite are entities too, `root` for example is a composite, also if look at demo project `level-3-skull` is a composite and you can get entity from it. Is the project exporting correctly?

Regarding box2d bodies inside composites isn't possible, becuase objects chenge their coordinates inside, so box2d cannot work properly

**Comment by aallnneess** [comment]
yeah, i was to fast with writing here, it works:

        // test Composite entity to take action to box2d etc.
        Entity testComp = root.getChild("testComp").getEntity();

        // test ItemWrapper to become the child sprite animation
        ItemWrapper testItem = root.getChild("testComp");

        // init testSprite Entity from composite
        Entity testSprite = testItem.getChild("testSprite").getEntity();
