### ISSUE TITLE
Double click to open composite in Editor

### ISSUE THREAD

**Issue by aallnneess** [rednblackgames/HyperLap2D#35]
It would be nice if you could get into the "composite mode" by double-clicking on the composite in the Editor Tree:

![image](https://user-images.githubusercontent.com/73443724/111791891-f8da7a00-88c3-11eb-8f41-086955a9f364.png)

**Comment by fgnm** [comment]
Made it few days ago but forget to push https://github.com/rednblackgames/HyperLap2D/commit/33f8b48fba416d79150f8c9b7d05a24a7d61261f :D
