### ISSUE TITLE
Box2d Fixture shifts when resize the Game

### ISSUE THREAD

**Issue by aallnneess** [rednblackgames/HyperLap2D#38]
**Describe the bug**
Box2d Fixture shifts when resize the Game. So, in case of using a mouse-joint, there are some problems:

https://user-images.githubusercontent.com/73443724/112603266-0daf9400-8e15-11eb-985f-c8603881fece.mp4
https://user-images.githubusercontent.com/73443724/112603275-130cde80-8e15-11eb-8b60-f65a72283e4b.mp4

**To Reproduce**
1. Create Body in Hyperlap
2. Create mouse joint inside Code
3. Start Desktop App. Fixture - mouse-joint works fine.
4. Resize Game. Fixture dont match the body anymore.

Latest Snapshot
Windows

**Comment by fgnm** [comment]
Not a issue :P
