### ISSUE TITLE
Copy Actions in the resources windows

### ISSUE THREAD

**Issue by aallnneess** [rednblackgames/HyperLap2D#39]
It would be nice if it was possible to copy actions. So far you can only delete them.

![image](https://user-images.githubusercontent.com/73443724/112612059-c9c18c80-8e1e-11eb-9f7d-db8a4017b70f.png)

**Comment by fgnm** [comment]
With copy you mean duplicate? Or copy and paste where?

**Comment by aallnneess** [comment]
yes, duplicate the action inside the resources-action panel. 

Or copy the content of an action, create a new empty one, and then paste it?
