### ISSUE TITLE
Cannot run on Windows 10

### ISSUE THREAD

**Issue by xerikssonx** [rednblackgames/HyperLap2D#48]
**Describe the bug**
Cannot run HyperLab2D on Windows 10

**To Reproduce**
1. Go to 'HyperLap2D.exe'
2. Click on 'HyperLap2D.exe'
3. See error

**Expected behavior**
Application is started

**Screenshots**
![image](https://user-images.githubusercontent.com/7081073/119320275-17723e00-bc84-11eb-9d78-519f35531efa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - HyperLap2D Version [e.g. 0.0.6]

**Runtime (please complete the following information):**
 - Device: HP Omen Laptop
 - OS: Windows 10
 - Runtime Version e.g. 0.0.6

**Additional context**

**Comment by fgnm** [comment]
Could you please check what's inside the folder `C:\Users\<username>\AppData\Roaming\.hyperlap2d\`?

There should be:
- `cache` directory with a `license.html` file inside
- `configs` directory that should contains: `config.pit` file and an empty `keymaps` directory

**Comment by xerikssonx** [comment]
@fgnm there are:

configs -> config.pit
crash -> java-hyperlog.txt

That's all

**Comment by xerikssonx** [comment]
One more weird thing:
In app folder there is folder with name "null" with "licenses.html" file inside
![image](https://user-images.githubusercontent.com/7081073/119324472-8a7db380-bc88-11eb-8c71-ce46ab4001e5.png)

**Comment by xerikssonx** [comment]
It try to find folder "keymap" but it does not exists

**Comment by fgnm** [comment]
I see, I'm trying to reproduce but can't get the crash.. Try to create the keymaps folder inside `C:\Users\<username>\AppData\Roaming\.hyperlap2d\configs`, it should be just an empty directory

**Comment by fgnm** [comment]
Check also if you have `C:\Users\<username>\Documents\HyperLap2D` folder (should be empty too)

**Comment by xerikssonx** [comment]
1. 
![image](https://user-images.githubusercontent.com/7081073/119328531-e0ecf100-bc8c-11eb-9b87-36e5ffc8be26.png)

2. There is no folder HyperLap2D documents

**Comment by fgnm** [comment]
@xerikssonx could you try this latest snapshot? https://github.com/rednblackgames/HyperLap2D/actions/runs/872599525

Thanks!

**Comment by xerikssonx** [comment]
@fgnm fixed)) thanks))
