### ISSUE TITLE
Complete Spriter support

### ISSUE THREAD

**Issue by fgnm** [rednblackgames/HyperLap2D#5]
Spriter Animation support is very experimental, still miss many features, but I don't own nor use Spriter, so if someone needs it feel free to add to this issue.

**Comment by fgnm** [comment]
Spriter support was discontinued with 074d760, I can't see any benefit with that.. Gdx implementation is old and not updated, many troubles with GWT, Spriter2 was announced years ago but still not released.

Instead, might be much more useful `DragonBones` or `Rive` support.

**Comment by aallnneess** [comment]
I use Spriter and as a free (or very cheap) alternative to Spine with a large asset library, this should also be interesting for other users, right?

Unfortunately with version 1 there is still no possibility to export / convert Spriter projects to Spine ....

**Comment by fgnm** [comment]
As I said `DragonBones` or `Rive` are much more interesting alternative to Spine if we want something free. Spriter 2 is in pre-order for almost 3 years and still not released.. That's not good.
`gdx-animation` looks better then Trixt0r's one, but again, no GWT.. Anyway, if you can work on to create a good runtime for Spriter in libgdx I'll be happy to integrate it in hyperlap as an extension like Spine or Talos :)
