### ISSUE TITLE
[Crash] Hyperlap crash if you change from or to monospace.

### ISSUE THREAD

**Issue by lazynessmind** [rednblackgames/HyperLap2D#78]
**Describe the bug**
When you change the font to monospace and preview hyperlap crashs. If you reopen it and see the live preview again it works. This is probably the skin not being reload when you change the lable from or to monospace,

**To Reproduce**
1. Add a label.
2. Change to monospace
3. Click to live preview.

**Expected behavior**
Not crash idk. lol

**Screenshots**
![Screenshot from 2022-04-27 18-52-31](https://user-images.githubusercontent.com/52864251/165589634-e924209d-28cb-4b7a-b1cf-e66bf57dcffd.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - HyperLap2D Version 0.0.8

**Runtime (please complete the following information):**
 - Device: Desktop
 - OS: Linux
 - Runtime Version: 0.0.8

**Additional context**
None

**Comment by fgnm** [comment]
Thanks for the report! The issue you point out is already fixed in latest snapshots :) which are also very near to first beta (I'm waiting the upcoming libGDX release).. I'd say, right now, snapshots are much more stable than every previous release, so you might give a try
