### ISSUE TITLE
Changing the width and height of a primitive doesn't work

### ISSUE THREAD

**Issue by Klemms** [rednblackgames/HyperLap2D#79]
**Describe the bug**
In the hyperlap editor, if you try to change the width and height of a primitive, nothing happens.
(Also note that changing the scale isn't the same as changing the size)

**To Reproduce**
1. Create a new primitive
2. Try to change it's width or height
3. Size doesn't change

**Expected behavior**
Size changes

**Desktop (please complete the following information):**
 - OS: Windows
 - HyperLap2D Version 0.1.0

**Comment by fgnm** [comment]
That's right, because primitives are controlled by a polygon shape which automatically adjust their sizes. To modify a primitive (not only width/height but also its shape) use the `Polygon Tool` ;)
