### ISSUE TITLE
main window size

### ISSUE THREAD

**Issue by java3000** [rednblackgames/HyperLap2D#81]
This(below) resolution is not enought to place whole program window, so bottom line is unaccessible
And there is no any chance for me to reduce window size vertically.

system: Ubuntu 22.04 LTS
program version: 0.1.1 from github deb
dimensions: 
xdpyinfo | grep 'dimensions:'
  dimensions:    1366x768 pixels (361x203 millimeters)

**Comment by fgnm** [comment]
Uhm never thought that 920x800 minimum window size could be an issue.. But yes it makes sense to reduce it to fit at least the 720p HD definition.. I'll fix tomorrow, as I think some minor adjustments to GUI will probably needs

**Comment by fgnm** [comment]
@java3000 you can download the latest snapshots from GH Actions or from the website https://hyperlap2d.rednblack.games/download
1366x768 is not the best solution to work with, but should works.. I'd suggest also to increase a little bit the UI Scale density (`File -> Settings -> General) maybe at 1.1x or 1.2x :)

**Comment by java3000** [comment]
> @java3000 you can download the latest snapshots from GH Actions or from the website https://hyperlap2d.rednblack.games/download 1366x768 is not the best solution to work with, but should works.. I'd suggest also to increase a little bit the UI Scale density (`File -> Settings -> General) maybe at 1.1x or 1.2x :)

downloaded and tested. Works perfectly. Now I can create scenes :)
