### ISSUE TITLE
Side scrolling too slow using touchpad

### ISSUE THREAD

**Issue by BestDragonApps** [rednblackgames/HyperLap2D#93]
**Describe the bug**
The sideways scrolling of the scene is too slow.
When I scroll through the scene, the camera only moves one pixel, so the single action of moving from side to side on the touchpad only moves the camera about 1% of the entire screen. It's too low, I have to scroll 10 times to move the editor camera to the next 10% portion.

**To Reproduce**
1. Open any project
2. Place the cursor on a scrollable part on the scene editor
3. Scroll using the touchpad

**Expected behavior**
The scroll should trigger a much larger movement.

**Device:**
 - OS: Ubuntu 22.04.6 LTS
 - HyperLap2D Version: 0.1.3
 - Device: Lenovo Thinkpad E495

**Additional context**
Scrolling in all other apps is ok and fast, so the problem cannot be related to any of my OS settings.
The zoom, on the other hand, is quite fast.
I cannot use/try with a mouse, I use only the touchpad.

There is a setting I can use to solve this issue? There is no setting for that in the App settings.

It would be helpful if I can increase the scroll distance by holding down the shift key on the keyboard.

Thanks

**Comment by fgnm** [comment]
Just add a scroll velocity setting in `Settings -> Sandbox -> Scroll Velocity` for faster scrolling needs :)
It was a very old hard coded value, good point to have it variable. You find it already in the latest snapshots. Anyway v0.1.3 is quite old, I advice to upgrade!

**Comment by BestDragonApps** [comment]
Thanks, I'll try it.
